In [1]:
import pandas as pd

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [ ]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [ ]:
pd.__version__

'2.3.1'

In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)>

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[2]

np.int64(3)

In [ ]:
a[2] = 10

In [ ]:
a[2]

np.int64(10)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n(2)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
n[0,1]

np.int64(2)

In [ ]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [1]:
u = np.array[1,2,3,4]

v = nn.array[0,1,0,1]

u + v

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
u = np.array([1,2,3,4])
v = np.array([0,1,0,1])

u + v

array([1, 3, 3, 5])

In [5]:
u

array([1, 2, 3, 4])

In [6]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] # shape outputs a tuple

    n = u.shape[0];

    result = 0.0;

    for i in range(n):
        result = result + u[i] * v[i];
    return result

In [19]:
vector_vector_multiplication(u, v)

np.float64(6.0)

In [9]:
U = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,1,2,3]]);

In [10]:
U

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [11]:
v

array([0, 1, 0, 1])

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0];

    num_rows = U.shape[0];

    result = np.zeros(num_rows);

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v);
    return result

In [18]:
matrix_vector_multiplication(U,v);

In [15]:
U

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [16]:
v

array([0, 1, 0, 1])

In [20]:
v = np.array([1,2,3,4])

In [21]:
matrix_vector_multiplication(U, v)

array([30., 70., 29.])

In [22]:
U.dot(v)

array([30, 70, 29])

In [23]:
V = np.array([
            [1,1,2],
            [0,0.5,1],
            [0,2,1],
            [1,2,0]
])

In [24]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [1. , 2. , 0. ]])

In [25]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0];

    num_rows = U.shape[0];
    num_columns = V.shape[1];

    result = np.zeros((num_rows, num_columns));

    for i in range(num_columns):
        vi = V[:, i]; # : denotes all rows
        Uvi = matrix_vector_multiplication(U, vi);
        result[:, i] = Uvi;
    
    return result;

In [26]:
matrix_matrix_multiplication(U, V)

array([[ 5. , 16. ,  7. ],
       [13. , 38. , 23. ],
       [12. , 19.5, 21. ]])

In [27]:
U.dot(V)

array([[ 5. , 16. ,  7. ],
       [13. , 38. , 23. ],
       [12. , 19.5, 21. ]])

In [28]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [1. , 2. , 0. ]])

In [ ]:
V[[0,1,2]] # get only the first three rows of V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [30]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [32]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [33]:
V*Vs_inv

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [36]:
matrix_matrix_multiplication(Vs, Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
pd

NameError: name 'pd' is not defined

In [38]:
import pandas as pd

In [40]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [41]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
df.Make # in Pandas, a DF is a collection of Series. Series = Columns

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [44]:
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [45]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [46]:
df[2,3]

KeyError: (2, 3)

In [48]:
df.loc[[2,3]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2  Lotus   Elise  2010      218.0                 4            MANUAL   
3    GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
2   convertible  54990  
3       4dr SUV  34450

In [49]:
pd.__version__

'2.3.1'

In [50]:
hwdf = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
hwdf

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [51]:
hwdf.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [52]:
hwdf.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [53]:
hwdf.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [56]:
hwdf[
    hwdf['origin'] == 'Asia'
]

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [57]:
hwdf.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [58]:
hwdf.horsepower.median();

In [60]:
hwdf['horsepower'].median()

np.float64(149.0)

In [61]:
hwdf['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [64]:
hwdf_hp_filled = hwdf['horsepower'].fillna(152.0)
hwdf_hp_filled

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [65]:
hwdf_hp_filled.isnull().sum()

np.int64(0)

In [67]:
hwdf_hp_filled.median()

np.float64(152.0)

In [69]:
hwdf_asia = hwdf[
    hwdf['origin'] == 'Asia'
]

hwdf_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [98]:
hwdf_asia_vw = hwdf_asia[['vehicle_weight']]
hwdf_asia_vw

vehicle_weight
8        2714.219310
12       2783.868974
14       3582.687368
20       2231.808142
21       2659.431451
...              ...
9688     3948.404625
9692     3680.341381
9693     2545.070139
9698     3107.427820
9703     2908.043477

[3247 rows x 1 columns]

In [99]:
hwdf_asia_vw_firstseven = hwdf_asia_vw.head(7)
hwdf_asia_vw_firstseven

vehicle_weight
8      2714.219310
12     2783.868974
14     3582.687368
20     2231.808142
21     2659.431451
34     2844.227534
38     3761.994038

In [100]:
X = hwdf_asia_vw_firstseven.values
X

array([[2714.21930965],
       [2783.86897424],
       [3582.68736772],
       [2231.8081416 ],
       [2659.43145076],
       [2844.22753389],
       [3761.99403819]])

In [101]:
XTX = matrix_matrix_multiplication(X,X.T)
XTX

array([[ 7366986.46085133,  7556030.92541486,  9724199.23387465,
         6057616.75336224,  7218280.19632533,  7719857.29349753,
        10210876.86123177],
       [ 7556030.92541486,  7749926.46575708,  9973732.20739725,
         6213061.44187306,  7403508.70489329,  7917956.78727446,
        10472898.48421337],
       [ 9724199.23387465,  9973732.20739725, 12835648.77478558,
         7995870.83608462,  9527911.463935  , 10189978.05656009,
        13478048.51805091],
       [ 6057616.75336224,  6213061.44187306,  7995870.83608462,
         4980967.58092514,  5935340.7638366 ,  6347770.16669749,
         8396048.9230991 ],
       [ 7218280.19632533,  7403508.70489329,  9527911.463935  ,
         5935340.7638366 ,  7072575.64128077,  7564028.15672766,
        10004765.26273247],
       [ 7719857.29349753,  7917956.78727446, 10189978.05656009,
         6347770.16669749,  7564028.15672766,  8089630.2645139 ,
        10699967.02574041],
       [10210876.86123177, 10472898.48421337, 134780

In [102]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[-1.25609295e+08,  3.76400375e+08, -3.37833720e+08,
        -4.58024199e+08, -1.49487067e+08, -2.18394587e+08,
         6.76335758e+08],
       [ 3.57913941e+08, -5.36870912e+08, -2.68435456e+08,
         7.15827883e+08, -7.15827883e+08,  1.07374182e+09,
        -3.35731449e+08],
       [ 1.78956971e+08, -5.36870912e+08, -2.68435456e+08,
         8.94784853e+08,  1.78956971e+08, -0.00000000e+00,
        -1.33530725e+08],
       [-0.00000000e+00,  1.07374182e+09,  5.36870912e+08,
        -1.07374182e+09, -0.00000000e+00, -1.07374182e+09,
         1.42944038e+08],
       [-3.57913941e+08, -0.00000000e+00,  5.36870912e+08,
        -7.15827883e+08, -3.57913941e+08, -0.00000000e+00,
         4.24629696e+08],
       [-3.57913941e+08,  0.00000000e+00,  0.00000000e+00,
         3.57913941e+08,  7.15827883e+08,  0.00000000e+00,
        -4.60137226e+08],
       [ 1.78956971e+08,  0.00000000e+00,  0.00000000e+00,
        -1.78956971e+08,  1.78956971e+08,  0.00000000e+00,
        -1.4945654

In [103]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [110]:
w = XTX_inv.dot(X)
w

array([[-7.32421875e-04],
       [-1.98364258e-04],
       [ 7.62939453e-05],
       [ 4.88281250e-04],
       [-1.22070312e-04],
       [ 3.35693359e-04],
       [ 4.57763672e-05]])

In [111]:
w.dot(y)

ValueError: shapes (7,1) and (7,) not aligned: 1 (dim 1) != 7 (dim 0)